package com.sohohouse.seven.more.contact

import com.sohohouse.seven.R


class EnquiryMap {
    companion object {
        fun getTopLevelEnquiryType(): EnquiryType {
            return EnquiryType(
                "",
                -1,
                R.string.enquiry_level_one_header,
                R.string.enquiry_reason_general_enquiry,
                generateTopLevel()
            )
        }

        private fun generateTopLevel(): MutableList<EnquiryType> {
            return mutableListOf(
                EnquiryType(
                    "GENERAL_ENQUIRY",
                    0,
                    R.string.enquiry_level_two_header,
                    R.string.enquiry_reason_general_enquiry,
                    generateLevelTwoGeneral()
                ),
                EnquiryType(
                    "TECHNICAL_ENQUIRY",
                    0,
                    R.string.enquiry_level_two_header,
                    R.string.enquiry_reason_technical_support,
                    generateLevelTwoTechnical()
                ),
                EnquiryType(
                    "MEMBERSHIP_ENQUIRY",
                    0,
                    R.string.enquiry_level_two_header,
                    R.string.enquiry_reason_membership_enquiry,
                    generateLevelTwoMembership()
                ),
                EnquiryType(
                    "RESERVATION_ENQUIRY",
                    0,
                    R.string.enquiry_level_two_header,
                    R.string.enquiry_reason_reservation_enquiry,
                    generateLevelTwoReservation()
                ),
                EnquiryType(
                    "EVENT_ENQUIRY",
                    0,
                    R.string.enquiry_level_two_header,
                    R.string.enquiry_reason_event_enquiry,
                    generateLevelTwoEvent()
                )
            )
        }

        // LEVEL TWO
        fun generateLevelTwoGeneral(): MutableList<EnquiryType> {
            return mutableListOf(
                EnquiryType(
                    "POSITIVE_FEEDBACK",
                    1,
                    R.string.enquiry_level_two_header,
                    R.string.enquiry_general_positive_feedback_label,
                    null
                ),
                EnquiryType(
                    "COMPLAINT",
                    1,
                    R.string.enquiry_level_two_header,
                    R.string.enquiry_general_complaint_label,
                    null
                ),
                EnquiryType(
                    "PRESS",
                    1,
                    R.string.enquiry_level_two_header,
                    R.string.enquiry_general_press_label,
                    null
                ),
                EnquiryType(
                    "PRIVACY",
                    1,
                    R.string.enquiry_level_two_header,
                    R.string.enquiry_general_data_label,
                    null
                ),
                EnquiryType(
                    "QUESTION",
                    1,
                    R.string.enquiry_level_two_header,
                    R.string.enquiry_general_question_label,
                    null
                ),
                EnquiryType(
                    "SUGGESTION",
                    1,
                    R.string.enquiry_level_two_header,
                    R.string.enquiry_general_suggestion_label,
                    null
                ),
                EnquiryType(
                    "OTHER",
                    1,
                    R.string.enquiry_level_two_header,
                    R.string.enquiry_general_other_label,
                    null
                )
            )
        }

        private fun generateLevelTwoTechnical(): MutableList<EnquiryType> {
            return mutableListOf(
                EnquiryType(
                    "NOTIFICATION_ISSUE",
                    1,
                    R.string.enquiry_level_two_header,
                    R.string.enquiry_technical_notification_label,
                    null
                ),
                EnquiryType(
                    "LOG_IN",
                    1,
                    R.string.enquiry_level_two_header,
                    R.string.enquiry_technical_login_label,
                    null
                ),
                EnquiryType(
                    "PAYMENT",
                    1,
                    R.string.enquiry_level_two_header,
                    R.string.enquiry_technical_payment_label,
                    null
                ),
                EnquiryType(
                    "HELP",
                    1,
                    R.string.enquiry_level_two_header,
                    R.string.enquiry_technical_help_label,
                    null
                ),
                EnquiryType(
                    "SCREENING",
                    1,
                    R.string.enquiry_level_two_header,
                    R.string.enquiry_technical_screening_label,
                    null
                ),
                EnquiryType(
                    "GYM_CREDITS",
                    1,
                    R.string.enquiry_level_two_header,
                    R.string.enquiry_technical_gym_label,
                    null
                ),
                EnquiryType(
                    "EVENT_BOOKING",
                    1,
                    R.string.enquiry_level_two_header,
                    R.string.enquiry_technical_event_label,
                    null
                ),
                EnquiryType(
                    "ROOM_BOOKING",
                    1,
                    R.string.enquiry_level_two_header,
                    R.string.enquiry_technical_room_label,
                    null
                ),
                EnquiryType(
                    "OTHER",
                    1,
                    R.string.enquiry_level_two_header,
                    R.string.enquiry_technical_other_label,
                    null
                )
            )
        }

        private fun generateLevelTwoMembership(): MutableList<EnquiryType> {
            return mutableListOf(
                EnquiryType(
                    "PAYMENTS",
                    1,
                    R.string.enquiry_level_two_header,
                    R.string.enquiry_membership_notification_label,
                    null
                ),
                EnquiryType(
                    "DETAILS",
                    1,
                    R.string.enquiry_level_two_header,
                    R.string.enquiry_membership_details_label,
                    null
                ),
                EnquiryType(
                    "GUEST_LIST",
                    1,
                    R.string.enquiry_level_two_header,
                    R.string.enquiry_membership_guest_list_label,
                    null
                ),
                EnquiryType(
                    "INDUCTION",
                    1,
                    R.string.enquiry_level_two_header,
                    R.string.enquiry_membership_inductions_label,
                    null
                ),
                EnquiryType(
                    "CHANGE",
                    1,
                    R.string.enquiry_level_two_header,
                    R.string.enquiry_membership_changes_label,
                    null
                ),
                EnquiryType(
                    "LOST_CARD",
                    1,
                    R.string.enquiry_level_two_header,
                    R.string.enquiry_membership_lost_card_label,
                    null
                ),
                EnquiryType(
                    "QUESTION",
                    1,
                    R.string.enquiry_level_two_header,
                    R.string.enquiry_membership_question_label,
                    null
                ),
                EnquiryType(
                    "ADD_ACTIVE_MEMBERSHIP",
                    1,
                    R.string.enquiry_level_two_header,
                    R.string.enquiry_add_active_membership,
                    null
                ),
                EnquiryType(
                    "OTHER",
                    1,
                    R.string.enquiry_level_two_header,
                    R.string.enquiry_membership_other_label,
                    null
                )
            )
        }

        private fun generateLevelTwoReservation(): MutableList<EnquiryType> {
            return mutableListOf(
                EnquiryType(
                    "NEW_RESERVATION",
                    1,
                    R.string.enquiry_level_three_reservation_header,
                    R.string.enquiry_reservation_new_label,
                    generateLevelThreeReservation()
                ),
                EnquiryType(
                    "EXISTING_RESERVATION",
                    1,
                    R.string.enquiry_level_three_reservation_header,
                    R.string.enquiry_reservation_existing_label,
                    generateLevelThreeReservation()
                ),
                EnquiryType(
                    "CANCELLATION",
                    1,
                    R.string.enquiry_level_three_reservation_header,
                    R.string.enquiry_reservation_cancellation_label,
                    generateLevelThreeReservation()
                ),
                EnquiryType(
                    "OTHER",
                    1,
                    R.string.enquiry_level_three_reservation_header,
                    R.string.enquiry_reservation_other_label,
                    null
                )
            )
        }

        private fun generateLevelTwoEvent(): MutableList<EnquiryType> {
            return mutableListOf(
                EnquiryType(
                    "MEMBER_EVENTS",
                    1,
                    R.string.enquiry_level_four_header,
                    R.string.enquiry_event_member_label,
                    generateLevelFourEvent()
                ),
                EnquiryType(
                    "MEMBER_SCREENINGS",
                    1,
                    R.string.enquiry_level_four_header,
                    R.string.enquiry_event_cinema_label,
                    generateLevelFourEventScreening()
                ),
                EnquiryType(
                    "CWH_EVENTS",
                    1,
                    R.string.enquiry_level_four_header,
                    R.string.enquiry_event_cwh_label,
                    generateLevelFourEventCwh()
                ),
                EnquiryType(
                    "GYM_CLASSES",
                    1,
                    R.string.enquiry_level_four_header,
                    R.string.enquiry_event_gym_label,
                    generateLevelFourEventGym()
                ),
                EnquiryType(
                    "PRIVATE_HIRE",
                    1,
                    R.string.enquiry_level_four_header,
                    R.string.enquiry_event_private_label,
                    generateLevelFourEventPrivate()
                )
            )
        }
        // END LEVEL TWO

        // LEVEL THREE
        private fun generateLevelThreeReservation(): MutableList<EnquiryType> {
            return mutableListOf(
                EnquiryType(
                    "BEDROOMS",
                    2,
                    R.string.enquiry_level_four_header,
                    R.string.enquiry_reservation_bedrooms_label,
                    generateLevelFourBedrooms()
                ),
                EnquiryType(
                    "RESTAURANT",
                    2,
                    R.string.enquiry_level_four_header,
                    R.string.enquiry_reservation_restaurant_label,
                    generateLevelFourRestaurants()
                ),
                EnquiryType(
                    "COWSHED",
                    2,
                    R.string.enquiry_level_four_header,
                    R.string.enquiry_reservation_cowshed_label,
                    generateLevelFourCowsheds()
                )
            )
        }
        // END LEVEL THREE

        // LEVEL FOUR
        private fun generateLevelFourBedrooms(): MutableList<EnquiryType> {
            return mutableListOf(
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.bedrooms_babington_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.bedrooms_dean_st_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.bedrooms_high_road_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.bedrooms_kettners_townhouse_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.bedrooms_lbh_barcelona_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.bedrooms_mayfair_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.bedrooms_redchurch_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.bedrooms_shoreditch_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.bedrooms_sbh_miami_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.bedrooms_farmhouse_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.bedrooms_amsterdam_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.bedrooms_barcelona_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.bedrooms_berlin_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.bedrooms_chicago_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.bedrooms_istanbul_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.bedrooms_mumbai_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.bedrooms_new_york_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.bedrooms_white_city_label,
                    null
                )
            )
        }

        private fun generateLevelFourRestaurants(): MutableList<EnquiryType> {
            return mutableListOf(
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_babington_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_cafe_boheme_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_cecconi_amsterdam_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_cecconi_barcelona_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_cecconi_berlin_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_cecconi_dumbo_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_cecconi_istanbul_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_cecconi_mayfair_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_cecconi_miami_beach_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_cecconi_mumbai_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_cecconi_shoreditch_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_cecconi_west_hollywood_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_dean_street_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_dumbo_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_electric_diner_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_electric_house_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_high_road_brasserie_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_high_road_house_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_hoxton_grill_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_kettners_townhouse_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_lbh_barcelona_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_lbh_malibu_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_lh_mayfair_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_ludlow_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_shoreditch_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_bh_miami_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_farmhouse_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_40_greek_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_76_dean_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_amsterdam_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_barcelona_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_berlin_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_chicago_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_istanbul_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_mumbai_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_new_york_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_toronto_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_west_hollywood_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_allis_chicago_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_allis_istanbul_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_allis_mumbai_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_allis_white_city_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.restaurant_white_city_label,
                    null
                )
            )
        }

        private fun generateLevelFourCowsheds(): MutableList<EnquiryType> {
            return mutableListOf(
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cowshed_babington_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cowshed_carnaby_st_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cowshed_clarendon_cross_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cowshed_primrose_hill_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cowshed_selfridges_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cowshed_shoreditch_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cowshed_farmhouse_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cowshed_amsterdam_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cowshed_barcelona_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cowshed_berlin_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cowshed_chicago_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cowshed_istanbul_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cowshed_miami_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cowshed_new_york_label,
                    null
                )
            )
        }

        private fun generateLevelFourEvent(): MutableList<EnquiryType> {
            return mutableListOf(
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.venue_babington_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.venue_dumbo_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.venue_electric_house_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.venue_high_road_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.venue_lbh_barcelona_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.venue_lbh_malibu_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.venue_mayfair_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.venue_ludlow_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.venue_shoreditch_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.venue_bh_miami_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.venue_farmhouse_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.venue_40_greek_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.venue_76_dean_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.venue_amsterdam_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.venue_barcelona_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.venue_berlin_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.venue_chicago_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.venue_istanbul_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.venue_mumbai_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.venue_new_york_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.venue_toronto_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.venue_west_hollywood_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.venue_white_city_label,
                    null
                )
            )
        }

        private fun generateLevelFourEventScreening(): MutableList<EnquiryType> {
            return mutableListOf(
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cinema_babington_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cinema_electric_barn_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cinema_portobello_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cinema_shoreditch_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cinema_white_city_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cinema_high_road_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cinema_lbh_barcelona_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cinema_lbh_malibu_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cinema_ludlow_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cinema_bh_miami_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cinema_76_dean_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cinema_amsterdam_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cinema_barcelona_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cinema_berlin_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cinema_chicago_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cinema_istanbul_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cinema_mumbai_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cinema_new_york_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cinema_toronto_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cinema_west_hollywood_label,
                    null
                )
            )
        }

        private fun generateLevelFourEventCwh(): MutableList<EnquiryType>? {
            return mutableListOf(
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cwh_aspen_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cwh_athens_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cwh_atlanta_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cwh_austin_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cwh_bangkok_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cwh_bogota_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cwh_boston_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cwh_buenos_aires_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cwh_copenhagen_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cwh_detroit_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cwh_dubai_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cwh_dublin_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cwh_hong_kong_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cwh_lisbon_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cwh_mexico_city_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cwh_milan_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cwh_montreal_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cwh_nashville_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cwh_new_orleans_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cwh_paris_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cwh_philadelphia_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cwh_portland_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cwh_rio_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cwh_rome_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cwh_san_francisco_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cwh_santa_barbara_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cwh_sao_paulo_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cwh_seattle_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cwh_shanghai_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cwh_singapore_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cwh_stockholm_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cwh_sydney_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cwh_tel_aviv_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cwh_tokyo_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cwh_vancouver_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cwh_warsaw_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cwh_washington_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.cwh_zurich_label,
                    null
                )
            )
        }

        private fun generateLevelFourEventGym(): MutableList<EnquiryType>? {
            return mutableListOf(
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.gym_dumbo_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.gym_farmhouse_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.gym_amsterdam_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.gym_barcelona_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.gym_berlin_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.gym_chicago_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.gym_istanbul_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.gym_mumbai_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.gym_new_york_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.gym_shoreditch_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.gym_toronto_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.gym_white_city_label,
                    null
                )
            )
        }

        private fun generateLevelFourEventPrivate(): MutableList<EnquiryType>? {
            return mutableListOf(
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.hire_babington_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.hire_cecconi_miami_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.hire_cecconi_west_hollywood_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.hire_dean_st_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.hire_portobello_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.hire_cinema_shoreditch_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.hire_cinema_white_city_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.hire_electric_house_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.hire_high_road_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.hire_hoxton_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.hire_kettners_townhouse_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.hire_bh_miami_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.hire_mayfair_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.hire_shoreditch_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.hire_bh_miami_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.hire_farmhouse_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.hire_40_greek_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.hire_76_dean_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.hire_amsterdam_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.hire_barcelona_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.hire_berlin_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.hire_chicago_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.hire_istanbul_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.hire_mumbai_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.hire_new_york_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.hire_west_hollywood_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.hire_white_city_label,
                    null
                ),
                EnquiryType(
                    "",
                    3,
                    R.string.enquiry_level_four_header,
                    R.string.hire_white_city_studio_label,
                    null
                )
            )
        }
        // END LEVEL FOUR
    }
}
